version: "3.9"

services:
  users-app:
    build: .
    container_name: users-app
    depends_on:
      - database-users
    ports:
      - 3002:3002
    env_file:
      - ./.env
    networks:
      - ilia-network

  database-users:
    image: bitnami/mongodb:5.0.17
    volumes:
      - mongodb_data:/bitnami/mongodb
    ports:
      - 27017:27017
    env_file:
      - ./.env
    networks:
      - ilia-network

volumes:
  mongodb_data:
    driver: local

networks: 
  ilia-network:
    name: wallet-service_ilia-network
    external: true
