version: "3.9"

services:
  database-users:
    image: mongo
    container_name: database-users
    ports:
      - 27017:27017
    env_file:
      - ./.env
    volumes:
      - mongodbdata:/data/db
    networks:
      - ilia-network

volumes:
  mongodbdata:
    driver: local

networks: 
  ilia-network:
    name: wallet-service_ilia-network
    external: true
