version: "3.9"

services:
  database-users:
    image: bitnami/mongodb:5.0.17
    volumes:
      - mongodb_data:/bitnami/mongodb
    ports:
      - 27017:27017
    env_file:
      - ./.env
    networks:
      - ilia-network

volumes:
  mongodb_data:
    driver: local

networks: 
  ilia-network:
    name: wallet-service_ilia-network
    external: true
